name: Oracle Cloud ARM Snipe
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Install Dependencies
        run: composer install
        
      - name: Create Key File
        run: |
          echo "${{ secrets.OCI_KEY_FILE }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Run Snipe Script
        run: php index.php
        env:
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: ./private_key.pem
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          OCI_COMPARTMENT_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_SHAPE: VM.Standard.A1.Flex
          OCI_OCPU: 4
          OCI_MEMORY_IN_GBS: 24
          OCI_BOOT_VOLUME_SIZE_IN_GBS: 100
